--------------------------------------------------------
--  Constraints for Table ADMIN_DBA_LOG
--------------------------------------------------------

  ALTER TABLE "ADMIN_DBA_LOG" ADD CONSTRAINT "CKC_BASE_DAT_UPL_ADMIN_DB" CHECK (BASE_DAT_UPL IS NULL OR (BASE_DAT_UPL IN ('Y','N'))) ENABLE;
 
  ALTER TABLE "ADMIN_DBA_LOG" ADD CONSTRAINT "CKC_BASE_TRSL_UPL_ADMIN_DB" CHECK (BASE_TRSL_UPL IS NULL OR (BASE_TRSL_UPL IN ('Y','N'))) ENABLE;
 
  ALTER TABLE "ADMIN_DBA_LOG" ADD CONSTRAINT "PK_ADMIN_DBA_LOG" PRIMARY KEY ("DBA_LOG_ID") ENABLE;
 
  ALTER TABLE "ADMIN_DBA_LOG" MODIFY ("DBA_LOG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN_DBA_LOG" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN_DBA_LOG" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
