--------------------------------------------------------
--  DDL for View APEXLIB_V_PAGE_BRANCH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "APEXLIB_V_PAGE_BRANCH" ("ID", "APPLICATION_ID", "PAGE_ID", "BRANCH_POINT", "BRANCH_ACTION", "WHEN_BUTTON_PRESSED", "WHEN_BUTTON_PRESSED_ID", "PROCESS_SEQUENCE", "CONDITION_TYPE", "CONDITION_EXPRESSION1", "CONDITION_EXPRESSION2", "NOT_AUTHORIZATION", "AUTHORIZATION_SCHEME") AS 
  SELECT BRANCH_ID             AS ID
     , APPLICATION_ID
     , PAGE_ID
     , BRANCH_POINT
     , BRANCH_ACTION
     , WHEN_BUTTON_PRESSED
     , BRANCH_WHEN_BUTTON_ID AS WHEN_BUTTON_PRESSED_ID
     , PROCESS_SEQUENCE
     , CONDITION_TYPE
     , CONDITION_EXPRESSION1
     , CONDITION_EXPRESSION2
     , CASE SUBSTR(AUTHORIZATION_SCHEME, 1, 4)
           WHEN 'Not ' THEN 'YES'
           ELSE             'NO'
       END                   AS NOT_AUTHORIZATION
     , LTRIM
         ( AUTHORIZATION_SCHEME
         , 'Not '
         )                   AS AUTHORIZATION_SCHEME
  FROM APEX_APPLICATION_PAGE_BRANCHES;
