--------------------------------------------------------
--  DDL for Package BASE_PKG
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "BASE_PKG" 
AS
  V_USER VARCHAR2(1000)              :=NVL(V('APP_USER'),USER);
  DENTAL_VERSION varchar2(100)       :='DentalSoft v0.6';
  MENU_EDIT_MODE BOOLEAN             := false;
  EDIT_USER VARCHAR2(1000);
  
FUNCTION SUBJECTIV_ALT_F 
  return number;

FUNCTION "USER_IS_IN_ROLE" (p_user_id IN INT,p_role_id IN INT) RETURN BOOLEAN; 
FUNCTION "AUTH"(
    p_username IN VARCHAR2,
    p_password IN VARCHAR2)
  RETURN BOOLEAN;
FUNCTION custom_hash(
    p_username IN VARCHAR2,
    p_password IN VARCHAR2)
  RETURN VARCHAR2;
FUNCTION TYPE_SUBTREE (p_type DM_SUPER_TYP.SUPER_TYP_ID%type) return varchar2;  
FUNCTION DM_TRANSLATE_F(
    p_TBL_NAME vt_DM_TRANSLATE.TBL_NAME%type ,
    p_TBL_COL_NAME vt_DM_TRANSLATE.TBL_COL_NAME%type ,
    p_TBL_PK_ID vt_DM_TRANSLATE.TBL_PK_ID%type ,
    p_LANGUAGE_ID vt_DM_TRANSLATE.LANGUAGE_ID%type )
  RETURN vt_DM_TRANSLATE.NAMES%type;
PROCEDURE DM_TRANSLATE_NAME_UPD(
    p_TBL_NAME vt_DM_TRANSLATE.TBL_NAME%type ,
    p_TBL_COL_NAME vt_DM_TRANSLATE.TBL_COL_NAME%type ,
    p_TBL_PK_ID vt_DM_TRANSLATE.TBL_PK_ID%type ,
    p_LANGUAGE_ID vt_DM_TRANSLATE.LANGUAGE_ID%type ,
    p_NAME vt_DM_TRANSLATE.NAMES%type );
PROCEDURE DM_TRANSLATE_DEL(
    p_TBL_NAME vt_DM_TRANSLATE.TBL_NAME%type ,
    p_TBL_PK_ID vt_DM_TRANSLATE.TBL_PK_ID%type );
FUNCTION RIGHTS_READ_ROW_F(
    p_tab DM_REGULATION.TYPE_TABLE1%type ,
    p_ID NUMBER ,
    P_STAT DM_REGULATION.TYPE_VALUE1%type,
    p_typ DM_SUPER_TYP.SUPER_TYP_ID%type DEFAULT NULL ) --egyelõre subjectiv-nél
  RETURN VARCHAR2;
FUNCTION RIGHTS_field_display_f(
    p_tab DM_REGULATION.TYPE_TABLE2%type,
    p_col DM_REGULATION.TYPE_COLUMN2%type,
    p_TBL_PK_ID NUMBER DEFAULT NULL,                   --nem lehet a riport columnnál kezelni, view-ba lehetne
    P_STAT DM_REGULATION.TYPE_VALUE1%type DEFAULT NULL,--nem lehet a riport columnnál kezelni, view-ba lehetne
    p_menu DM_REGULATION.TYPE_VALUE1%type DEFAULT NULL,
    p_partype DM_SUPER_TYP.SUPER_TYP_ID%type DEFAULT NULL)
  RETURN VARCHAR2;
FUNCTION RIGHTS_field_updateable_f(
    p_tab DM_REGULATION.TYPE_TABLE2%type,
    p_col DM_REGULATION.TYPE_COLUMN2%type,
    p_TBL_PK_ID NUMBER ,
    P_STAT DM_REGULATION.TYPE_VALUE1%type,
    p_menu DM_REGULATION.TYPE_VALUE1%type DEFAULT NULL,
    p_partype DM_SUPER_TYP.SUPER_TYP_ID%type DEFAULT NULL)
  RETURN VARCHAR2;
FUNCTION v_LANG_F
  RETURN DM_LANGUAGE.LANGUAGE_ID%TYPE;
FUNCTION v_LANG_DEFAULT_F
  RETURN DM_LANGUAGE.LANGUAGE_ID%TYPE;
PROCEDURE v_LANG_set(
    p_lang DM_LANGUAGE.LANGUAGE_ID%TYPE);
FUNCTION LANGUAGE_NAME_F
  RETURN DM_LANGUAGE.LANGUAGE_NAME%TYPE;
PROCEDURE LANGUAGE_CHANGE(
    p_lang VARCHAR2);
FUNCTION SUBJECTIV_NAME_F(
    p_subj_id SUBJECT.SUBJ_ID%type)
  RETURN VARCHAR2;
FUNCTION SUBJECTIV_EPINAME_F(
    p_subj_id SUBJECT.SUBJ_ID%type)
  RETURN VARCHAR2;
FUNCTION SUBJECTIV_DATA_F(
    p_subj_id SUBJECT.SUBJ_ID%type)
  RETURN VARCHAR2;
  --function SUBJECTIV_STYPE_F (p_subj_id SUBJECTIV.SUBJ_ID%type) return varchar2;
  --function SUBJECTIV_STYPE_ID_F (p_subj_id SUBJECTIV.SUBJ_ID%type) return varchar2;

FUNCTION STATUS_DEFAULT_F (P_TAB dm_regulation.type_table1%type)
  RETURN NUMBER;

FUNCTION PARENT_SUBJ_ID_F(
    p_subj_id SUBJECT.SUBJ_ID%type)
  RETURN SUBJECT.SUBJ_ID%type;
FUNCTION SUBJECTIV_UK_F(
    p_subj_id SUBJECT.SUBJ_ID%type)
  RETURN VARCHAR2 DETERMINISTIC ;


PROCEDURE TREATM_REL_pkg ( 
  P_TREATM_ID1 TREATM_REL.TREATM_ID1%TYPE
 ,P_TREATM_ID2 TREATM_REL.TREATM_ID2%TYPE
 ,P_MODE varchar2 default 'I'); --I insert, U update, D delete

FUNCTION popup_pages
  RETURN VARCHAR2;
procedure image_display( p_mm_id mm_files.mm_id%type); 

FUNCTION VALUE_LIST_DM_SUPER_TYP (p_group_id NUMBER) RETURN VALUE_LIST PIPELINED;
FUNCTION VALUE_LIST_TREE_DM_SUPER_TYP (p_group_id NUMBER) RETURN VALUE_LIST PIPELINED;

END BASE_PKG;

/
