--------------------------------------------------------
--  Constraints for Table DM_ANALYSIS_TYP
--------------------------------------------------------

  ALTER TABLE "DM_ANALYSIS_TYP" ADD CONSTRAINT "CKC_SOPTIONAL_DM_ANALY" CHECK (SOPTIONAL IS NULL OR (SOPTIONAL IN ('Y','N','O'))) ENABLE;
 
  ALTER TABLE "DM_ANALYSIS_TYP" ADD CONSTRAINT "PK_DM_ANALYSIS_TYP" PRIMARY KEY ("ANALYSIS_TYPE_ID") DISABLE;
 
  ALTER TABLE "DM_ANALYSIS_TYP" MODIFY ("STATUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_ANALYSIS_TYP" MODIFY ("ANALYSIS_TYPE_ID" NOT NULL ENABLE);
