--------------------------------------------------------
--  DDL for Package DM_DOMAIN_RULE_TAPI
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "DM_DOMAIN_RULE_TAPI" 
IS
type DM_DOMAIN_RULE_tapi_rec
IS
  record
  (
    CRU DM_DOMAIN_RULE.CRU%type ,
    TO_DATE DM_DOMAIN_RULE.TO_DATE%type ,
    SUPER_GROUP_TREE DM_DOMAIN_RULE.SUPER_GROUP_TREE%type ,
    TARGET_TABLE_NAME DM_DOMAIN_RULE.TARGET_TABLE_NAME%type ,
    DESCRIPTION DM_DOMAIN_RULE.DESCRIPTION%type ,
    MDU DM_DOMAIN_RULE.MDU%type ,
    FROM_DATE DM_DOMAIN_RULE.FROM_DATE%type ,
    CRD DM_DOMAIN_RULE.CRD%type ,
    MDD DM_DOMAIN_RULE.MDD%type ,
    RULE_TYPE_ID DM_DOMAIN_RULE.RULE_TYPE_ID%type ,
    SUPER_GROUP_ID DM_DOMAIN_RULE.SUPER_GROUP_ID%type ,
    DOMAIN_RULE_ID DM_DOMAIN_RULE.DOMAIN_RULE_ID%type ,
    DOMAIN_ID DM_DOMAIN_RULE.DOMAIN_ID%type ,
    TARGET_COLUMN_NAME DM_DOMAIN_RULE.TARGET_COLUMN_NAME%type );
type DM_DOMAIN_RULE_tapi_tab
IS
  TABLE OF DM_DOMAIN_RULE_tapi_rec;
  -- insert
  PROCEDURE ins(
      p_CRU                IN DM_DOMAIN_RULE.CRU%type DEFAULT NULL ,
      p_TO_DATE            IN DM_DOMAIN_RULE.TO_DATE%type DEFAULT NULL ,
      p_SUPER_GROUP_TREE   IN DM_DOMAIN_RULE.SUPER_GROUP_TREE%type DEFAULT NULL ,
      p_TARGET_TABLE_NAME  IN DM_DOMAIN_RULE.TARGET_TABLE_NAME%type DEFAULT NULL ,
      p_DESCRIPTION        IN DM_DOMAIN_RULE.DESCRIPTION%type DEFAULT NULL ,
      p_MDU                IN DM_DOMAIN_RULE.MDU%type DEFAULT NULL ,
      p_FROM_DATE          IN DM_DOMAIN_RULE.FROM_DATE%type DEFAULT NULL ,
      p_CRD                IN DM_DOMAIN_RULE.CRD%type DEFAULT NULL ,
      p_MDD                IN DM_DOMAIN_RULE.MDD%type DEFAULT NULL ,
      p_RULE_TYPE_ID       IN DM_DOMAIN_RULE.RULE_TYPE_ID%type DEFAULT NULL ,
      p_SUPER_GROUP_ID     IN DM_DOMAIN_RULE.SUPER_GROUP_ID%type DEFAULT NULL ,
      p_DOMAIN_RULE_ID     IN DM_DOMAIN_RULE.DOMAIN_RULE_ID%type ,
      p_DOMAIN_ID          IN DM_DOMAIN_RULE.DOMAIN_ID%type ,
      p_TARGET_COLUMN_NAME IN DM_DOMAIN_RULE.TARGET_COLUMN_NAME%type DEFAULT NULL );
  -- update
  PROCEDURE upd(
      p_CRU                IN DM_DOMAIN_RULE.CRU%type DEFAULT NULL ,
      p_TO_DATE            IN DM_DOMAIN_RULE.TO_DATE%type DEFAULT NULL ,
      p_SUPER_GROUP_TREE   IN DM_DOMAIN_RULE.SUPER_GROUP_TREE%type DEFAULT NULL ,
      p_TARGET_TABLE_NAME  IN DM_DOMAIN_RULE.TARGET_TABLE_NAME%type DEFAULT NULL ,
      p_DESCRIPTION        IN DM_DOMAIN_RULE.DESCRIPTION%type DEFAULT NULL ,
      p_MDU                IN DM_DOMAIN_RULE.MDU%type DEFAULT NULL ,
      p_FROM_DATE          IN DM_DOMAIN_RULE.FROM_DATE%type DEFAULT NULL ,
      p_CRD                IN DM_DOMAIN_RULE.CRD%type DEFAULT NULL ,
      p_MDD                IN DM_DOMAIN_RULE.MDD%type DEFAULT NULL ,
      p_RULE_TYPE_ID       IN DM_DOMAIN_RULE.RULE_TYPE_ID%type DEFAULT NULL ,
      p_SUPER_GROUP_ID     IN DM_DOMAIN_RULE.SUPER_GROUP_ID%type DEFAULT NULL ,
      p_DOMAIN_RULE_ID     IN DM_DOMAIN_RULE.DOMAIN_RULE_ID%type ,
      p_DOMAIN_ID          IN DM_DOMAIN_RULE.DOMAIN_ID%type ,
      p_TARGET_COLUMN_NAME IN DM_DOMAIN_RULE.TARGET_COLUMN_NAME%type DEFAULT NULL );
  -- delete
  PROCEDURE del(
      p_DOMAIN_RULE_ID IN DM_DOMAIN_RULE.DOMAIN_RULE_ID%type );

  FUNCTION GET_GROUP(p_domain_id NUMBER,p_rule_type_id NUMBER, p_target_table_name VARCHAR2, p_target_column_name VARCHAR2) return number;
  FUNCTION GET_TREE(p_domain_id NUMBER,p_rule_type_id NUMBER, p_target_table_name VARCHAR2, p_target_column_name VARCHAR2) return number;
END DM_DOMAIN_RULE_tapi;

/
