--------------------------------------------------------
--  Constraints for Table DM_MESSAGE
--------------------------------------------------------

  ALTER TABLE "DM_MESSAGE" ADD CONSTRAINT "PK_DM_MESSAGE" PRIMARY KEY ("MESSAGE_ID") ENABLE;
 
  ALTER TABLE "DM_MESSAGE" MODIFY ("STATUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_MESSAGE" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_MESSAGE" MODIFY ("MESSAGE_TEXT" NOT NULL ENABLE);
 
  ALTER TABLE "DM_MESSAGE" MODIFY ("MESSAGE_TYPE_ID" NOT NULL ENABLE);
