--------------------------------------------------------
--  Constraints for Table DM_ROLE_USER
--------------------------------------------------------

  ALTER TABLE "DM_ROLE_USER" ADD CONSTRAINT "PK_DMRR" PRIMARY KEY ("ROLE_USER_ID") ENABLE;
 
  ALTER TABLE "DM_ROLE_USER" MODIFY ("ROLE_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_ROLE_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_ROLE_USER" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_ROLE_USER" MODIFY ("STATUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_ROLE_USER" ADD CONSTRAINT "UK_DMRR" UNIQUE ("USER_ID", "ROLE_ID", "DATA_OWNER_ID") ENABLE;
