--------------------------------------------------------
--  DDL for Package DM_SUPER_TYP_TAPI
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "DM_SUPER_TYP_TAPI" 
IS
type DM_SUPER_TYP_tapi_rec
IS
  record
  (
    CRU DM_SUPER_TYP.CRU%type ,
    SUPER_TYPE_NAME DM_SUPER_TYP.SUPER_TYPE_NAME%type ,
    WK_CLASS_ID DM_SUPER_TYP.WK_CLASS_ID%type ,
    GROUP_ID DM_SUPER_TYP.GROUP_ID%type ,
    TO_DATE DM_SUPER_TYP.TO_DATE%type ,
    DESCRIPTION DM_SUPER_TYP.DESCRIPTION%type ,
    MDU DM_SUPER_TYP.MDU%type ,
    GROUND_LEVEL_ID DM_SUPER_TYP.GROUND_LEVEL_ID%type ,
    SUPER_GROUP_NAME DM_SUPER_TYP.SUPER_GROUP_NAME%type ,
    SLEVEL DM_SUPER_TYP.SLEVEL%type ,
    FROM_DATE DM_SUPER_TYP.FROM_DATE%type ,
    SUPER_TYPE_SHORT_NAME DM_SUPER_TYP.SUPER_TYPE_SHORT_NAME%type ,
    CRD DM_SUPER_TYP.CRD%type ,
    MDD DM_SUPER_TYP.MDD%type ,
    ROLL_TYPE DM_SUPER_TYP.ROLL_TYPE%type ,
    USE_COMMENT DM_SUPER_TYP.USE_COMMENT%type ,
    WIRED_TO DM_SUPER_TYP.WIRED_TO%type ,
    SUPER_TYP_ID DM_SUPER_TYP.SUPER_TYP_ID%type );
type DM_SUPER_TYP_tapi_tab
IS
  TABLE OF DM_SUPER_TYP_tapi_rec;
  -- insert
  PROCEDURE ins(
      p_CRU                   IN DM_SUPER_TYP.CRU%type DEFAULT NULL ,
      p_SUPER_TYPE_NAME       IN DM_SUPER_TYP.SUPER_TYPE_NAME%type ,
      p_WK_CLASS_ID           IN DM_SUPER_TYP.WK_CLASS_ID%type DEFAULT NULL ,
      p_GROUP_ID              IN DM_SUPER_TYP.GROUP_ID%type DEFAULT NULL ,
      p_TO_DATE               IN DM_SUPER_TYP.TO_DATE%type ,
      p_DESCRIPTION           IN DM_SUPER_TYP.DESCRIPTION%type DEFAULT NULL ,
      p_MDU                   IN DM_SUPER_TYP.MDU%type DEFAULT NULL ,
      p_GROUND_LEVEL_ID       IN DM_SUPER_TYP.GROUND_LEVEL_ID%type ,
      p_SUPER_GROUP_NAME      IN DM_SUPER_TYP.SUPER_GROUP_NAME%type DEFAULT NULL ,
      p_SLEVEL                IN DM_SUPER_TYP.SLEVEL%type DEFAULT NULL ,
      p_FROM_DATE             IN DM_SUPER_TYP.FROM_DATE%type ,
      p_SUPER_TYPE_SHORT_NAME IN DM_SUPER_TYP.SUPER_TYPE_SHORT_NAME%type DEFAULT NULL ,
      p_CRD                   IN DM_SUPER_TYP.CRD%type DEFAULT NULL ,
      p_MDD                   IN DM_SUPER_TYP.MDD%type DEFAULT NULL ,
      p_ROLL_TYPE             IN DM_SUPER_TYP.ROLL_TYPE%type DEFAULT NULL ,
      p_USE_COMMENT           IN DM_SUPER_TYP.USE_COMMENT%type DEFAULT NULL ,
      p_WIRED_TO              IN DM_SUPER_TYP.WIRED_TO%type DEFAULT NULL ,
      p_SUPER_TYP_ID          IN DM_SUPER_TYP.SUPER_TYP_ID%type );
  -- update
  PROCEDURE upd(
      p_CRU                   IN DM_SUPER_TYP.CRU%type DEFAULT NULL ,
      p_SUPER_TYPE_NAME       IN DM_SUPER_TYP.SUPER_TYPE_NAME%type ,
      p_WK_CLASS_ID           IN DM_SUPER_TYP.WK_CLASS_ID%type DEFAULT NULL ,
      p_GROUP_ID              IN DM_SUPER_TYP.GROUP_ID%type DEFAULT NULL ,
      p_TO_DATE               IN DM_SUPER_TYP.TO_DATE%type ,
      p_DESCRIPTION           IN DM_SUPER_TYP.DESCRIPTION%type DEFAULT NULL ,
      p_MDU                   IN DM_SUPER_TYP.MDU%type DEFAULT NULL ,
      p_GROUND_LEVEL_ID       IN DM_SUPER_TYP.GROUND_LEVEL_ID%type ,
      p_SUPER_GROUP_NAME      IN DM_SUPER_TYP.SUPER_GROUP_NAME%type DEFAULT NULL ,
      p_SLEVEL                IN DM_SUPER_TYP.SLEVEL%type DEFAULT NULL ,
      p_FROM_DATE             IN DM_SUPER_TYP.FROM_DATE%type ,
      p_SUPER_TYPE_SHORT_NAME IN DM_SUPER_TYP.SUPER_TYPE_SHORT_NAME%type DEFAULT NULL ,
      p_CRD                   IN DM_SUPER_TYP.CRD%type DEFAULT NULL ,
      p_MDD                   IN DM_SUPER_TYP.MDD%type DEFAULT NULL ,
      p_ROLL_TYPE             IN DM_SUPER_TYP.ROLL_TYPE%type DEFAULT NULL ,
      p_USE_COMMENT           IN DM_SUPER_TYP.USE_COMMENT%type DEFAULT NULL ,
      p_WIRED_TO              IN DM_SUPER_TYP.WIRED_TO%type DEFAULT NULL ,
      p_SUPER_TYP_ID          IN DM_SUPER_TYP.SUPER_TYP_ID%type );
  -- delete
  PROCEDURE del(
      p_SUPER_TYP_ID IN DM_SUPER_TYP.SUPER_TYP_ID%type );

  FUNCTION LOOKUP_NAME (P_SUPER_TYPE_ID NUMBER,P_LANGUAGE_ID   NUMBER DEFAULT null)
  RETURN VARCHAR2;

  FUNCTION LOOKUP_NAME (p_short_name DM_SUPER_TYP.SUPER_TYPE_SHORT_NAME%TYPE,P_LANGUAGE_ID   NUMBER DEFAULT null)
  RETURN VARCHAR2;

END DM_SUPER_TYP_tapi;

/
