--------------------------------------------------------
--  Constraints for Table DM_SUPER_TYP
--------------------------------------------------------

  ALTER TABLE "DM_SUPER_TYP" ADD CONSTRAINT "DM_SUPER_TYP_PK" PRIMARY KEY ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "DM_SUPER_TYP" ADD CONSTRAINT "KEY_DM_SUPER_TYP_SUPER_TYPE_SH" UNIQUE ("SUPER_TYPE_SHORT_NAME") ENABLE;
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("SUPER_TYP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("GROUND_LEVEL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("SUPER_TYPE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("FROM_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("TO_DATE" NOT NULL ENABLE);
