--------------------------------------------------------
--  DDL for Table DM_SUBJECT
--------------------------------------------------------

  CREATE TABLE "DM_SUBJECT" 
   (	"DM_SUBJECT_ID" NUMBER(12,0), 
	"GROUP_ID" NUMBER(12,0), 
	"SUBJ_TYPE_ID" NUMBER(12,0), 
	"SUBJ_PARAM_TYPE_ID" NUMBER(12,0), 
	"ORDER_NO" NUMBER(4,0), 
	"MANDATORY" NUMBER(1,0) DEFAULT 0, 
	"IS_GROUP" NUMBER(1,0) DEFAULT 0, 
	"MULTIPLY" NUMBER(1,0) DEFAULT 0, 
	"APPENDABLE" NUMBER(1,0) DEFAULT 0, 
	"FIELD_TYPE" NVARCHAR2(50) DEFAULT 'TEXT', 
	"VALUE_GROUP_TABLE" NVARCHAR2(50) DEFAULT 'DM_SUPER_TYP', 
	"VALUE_GROUP_ID" NUMBER(12,0), 
	"DIMENSION_ALLOWED" NUMBER(1,0), 
	"DIMENSION_GROUP_ID" NUMBER(12,0), 
	"DESCRIPTION" VARCHAR2(255), 
	"CRD" TIMESTAMP (6), 
	"CRU" VARCHAR2(30), 
	"MDD" TIMESTAMP (6), 
	"MDU" VARCHAR2(30), 
	"FROM_DATE" DATE DEFAULT SYSDATE, 
	"TO_DATE" DATE DEFAULT TO_DATE('2099.12.31. 23:59:59','YYYY.MM.DD. HH24:MI:SS'), 
	"ROLL_TYPE" NUMBER(1,0) DEFAULT 0, 
	"TABLE_ROLL" NVARCHAR2(50) DEFAULT 'SUBJ_PARAM', 
	"MEDIA" NUMBER(1,0) DEFAULT 0
   ) ;
