--------------------------------------------------------
--  Constraints for Table EPI_REL
--------------------------------------------------------

  ALTER TABLE "EPI_REL" ADD CONSTRAINT "AK_PK_EPRE_EPI_REL" UNIQUE ("EPI_REL_ID") ENABLE;
 
  ALTER TABLE "EPI_REL" ADD CONSTRAINT "AK_UK_EPRE_EPI_REL" UNIQUE ("EPI_ID1", "EPI_ID2", "REL_TYPE_ID") ENABLE;
 
  ALTER TABLE "EPI_REL" MODIFY ("STATUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EPI_REL" MODIFY ("EPI_REL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EPI_REL" MODIFY ("EPI_ID1" NOT NULL ENABLE);
 
  ALTER TABLE "EPI_REL" MODIFY ("EPI_ID2" NOT NULL ENABLE);
 
  ALTER TABLE "EPI_REL" MODIFY ("REL_TYPE_ID" NOT NULL ENABLE);
