--------------------------------------------------------
--  Constraints for Table EPI_TREATM_PARAM
--------------------------------------------------------

  ALTER TABLE "EPI_TREATM_PARAM" ADD CONSTRAINT "PK_EPI_TREATM_PARAM" PRIMARY KEY ("EPI_TREATM_PARAM_ID") ENABLE;
 
  ALTER TABLE "EPI_TREATM_PARAM" MODIFY ("EPI_TREATM_PARAM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EPI_TREATM_PARAM" MODIFY ("EPI_TREAMT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EPI_TREATM_PARAM" MODIFY ("PARAM_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EPI_TREATM_PARAM" MODIFY ("STATUS_ID" NOT NULL ENABLE);
