--------------------------------------------------------
--  DDL for Type MENU_ITEM
--------------------------------------------------------

  CREATE OR REPLACE TYPE "MENU_ITEM" AS OBJECT (
  MENU_ID NUMBER,
  LVL NUMBER,
  LABEL NVARCHAR2(100),
  PAGE_ID NVARCHAR2(50),
  IS_CURRENT_LIST_ENTRY NVARCHAR2(255),
  IMAGE NVARCHAR2(255),
  IMAGE_ATTRIBUTE NVARCHAR2(255),
  IMAGE_ALT_ATTRIBUTE NVARCHAR2(255),
  ORDER1 NUMBER,
  ORDER2 NUMBER,
  TREATM_GROUP_ID NUMBER,
  APEX_VARIABLE NVARCHAR2(255),
  ROLL_TYPE NUMBER 
);

/
