REM INSERTING into MM_FILES
SET DEFINE OFF;
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('54',null,null,null,null,'image/png','Italy.png',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.35,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('55',null,null,null,null,'image/png',null,null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.35,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('1',null,null,null,null,'image/png','hungary',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.36,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('2',null,null,null,null,'image/png','united_kingdom',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.36,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('100',null,null,null,null,'image/png','Add.png',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.38,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('101',null,null,null,null,'image/png','Remove.png',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.38,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('51',null,null,null,null,'image/png','Hungary.png',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.38,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('52',null,null,null,null,'image/png','United_kingdom',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.39,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('53',null,null,null,null,'image/png','Germany',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.39,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('3',null,null,null,null,'image/png','germany',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.37,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('4',null,null,null,null,'image/png','italy',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.37,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('5',null,null,null,null,'image/png','france',null,null,'0',null,to_timestamp('15-AUG.  -04 07.52.37,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('1000',null,null,null,null,null,null,null,null,'0','OBH_TEST',to_timestamp('16-JAN.  -12 17.04.34,387507000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
Insert into MM_FILES (MM_ID,MM_TYPE_ID,SUBJ_ID,EPI_ID,MM_HYPL,MAIN_TYPE,FILE_NAME,MM_CHARSET,DESCRIPTION,ROLL_TYPE,CRU,CRD,MDU,MDD,TITLE,STAT_TYPE_ID,STATUS_ID) values ('1001',null,null,null,null,null,null,null,null,'0','OBH_TEST',to_timestamp('16-JAN.  -12 23.09.35,558038000','RR-MON-DD HH24.MI.SSXFF'),null,null,null,'5','912');
