--------------------------------------------------------
--  Constraints for Table PRT_IC_ITEM
--------------------------------------------------------

  ALTER TABLE "PRT_IC_ITEM" ADD CONSTRAINT "AK_UK_PICI_PRT_IC_I" UNIQUE ("IC_ID", "ORDER_NO", "IC_VALUE") ENABLE;
 
  ALTER TABLE "PRT_IC_ITEM" ADD CONSTRAINT "PK_ PICI" UNIQUE ("IC_ITEM_ID") ENABLE;
 
  ALTER TABLE "PRT_IC_ITEM" MODIFY ("IC_ITEM_ID" NOT NULL DISABLE);
 
  ALTER TABLE "PRT_IC_ITEM" MODIFY ("IC_ID" NOT NULL DISABLE);
 
  ALTER TABLE "PRT_IC_ITEM" MODIFY ("ORDER_NO" NOT NULL DISABLE);
 
  ALTER TABLE "PRT_IC_ITEM" MODIFY ("IC_VALUE" NOT NULL DISABLE);
