--------------------------------------------------------
--  Constraints for Table PRT_TREATM_REL
--------------------------------------------------------

  ALTER TABLE "PRT_TREATM_REL" ADD CONSTRAINT "PK_PRTR" UNIQUE ("TREATM_REL_ID") DISABLE;
 
  ALTER TABLE "PRT_TREATM_REL" MODIFY ("TREATM_REL_ID" NOT NULL DISABLE);
 
  ALTER TABLE "PRT_TREATM_REL" MODIFY ("TREATM_ID1" NOT NULL DISABLE);
 
  ALTER TABLE "PRT_TREATM_REL" MODIFY ("TREATM_ID2" NOT NULL DISABLE);
 
  ALTER TABLE "PRT_TREATM_REL" MODIFY ("REL_TYPE_ID" NOT NULL DISABLE);
 
  ALTER TABLE "PRT_TREATM_REL" ADD CONSTRAINT "UK_PRTR" PRIMARY KEY ("TREATM_ID1", "TREATM_ID2", "REL_TYPE_ID") DISABLE;
