--------------------------------------------------------
--  Constraints for Table SUBJECT_COPY
--------------------------------------------------------

  ALTER TABLE "SUBJECT_COPY" ADD CONSTRAINT "PK_SUBJECT_COPY" PRIMARY KEY ("SUBJ_ID") ENABLE;
 
  ALTER TABLE "SUBJECT_COPY" MODIFY ("SUBJ_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT_COPY" MODIFY ("FROM_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT_COPY" MODIFY ("TO_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT_COPY" MODIFY ("CRD" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT_COPY" MODIFY ("CRU" NOT NULL ENABLE);
