--------------------------------------------------------
--  Constraints for Table SUBJ_REL_COPY
--------------------------------------------------------

  ALTER TABLE "SUBJ_REL_COPY" ADD CONSTRAINT "PK_SUBJ_REL_COPY" PRIMARY KEY ("SUBJ_REL_ID") ENABLE;
 
  ALTER TABLE "SUBJ_REL_COPY" MODIFY ("SUBJ_REL_ID" NOT NULL DISABLE);
 
  ALTER TABLE "SUBJ_REL_COPY" MODIFY ("SUBJ_ID1" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJ_REL_COPY" MODIFY ("SUBJ_ID2" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJ_REL_COPY" MODIFY ("REL_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJ_REL_COPY" MODIFY ("CRU" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJ_REL_COPY" MODIFY ("CRD" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJ_REL_COPY" MODIFY ("FROM_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJ_REL_COPY" MODIFY ("TO_DATE" NOT NULL ENABLE);
