-- Unable to render TYPE DDL for object OBH_TEST.SYS_PLSQL_168552_112_1 with DBMS_METADATA attempting internal generator.
CREATE TYPE            SYS_PLSQL_168552_112_1 as object (YEAR NUMBER,
MONTH NUMBER,
DAY NUMBER,
DAYS_IN_MONTH NUMBER,
THE_DATE DATE);
