-- Unable to render TYPE DDL for object OBH_TEST.SYS_PLSQL_168573_104_1 with DBMS_METADATA attempting internal generator.
CREATE TYPE            SYS_PLSQL_168573_104_1 as object (SEQUENCE_NUMBER NUMBER,
FOLDER_ID VARCHAR2(2000),
DISPLAY_NAME VARCHAR2(2000),
TOTAL_COUNT NUMBER,
CHILD_FOLDER_COUNT NUMBER,
UNREAD_COUNT NUMBER);
