--------------------------------------------------------
--  DDL for Package TREATM_PARAM_TAPI
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "TREATM_PARAM_TAPI" 
IS
type TREATM_PARAM_tapi_rec
IS
  record
  (
    CRU TREATM_PARAM.CRU%type ,
    TREATM_PARAM_ID TREATM_PARAM.TREATM_PARAM_ID%type ,
    UNIT TREATM_PARAM.UNIT%type ,
    TO_DATE TREATM_PARAM.TO_DATE%type ,
    SUBJ_ID TREATM_PARAM.SUBJ_ID%type ,
    UNIT_TYPE_ID TREATM_PARAM.UNIT_TYPE_ID%type ,
    DESCRIPTION TREATM_PARAM.DESCRIPTION%type ,
    SUBJ_TYPE_ID TREATM_PARAM.SUBJ_TYPE_ID%type ,
    MDU TREATM_PARAM.MDU%type ,
    ORDER_NO TREATM_PARAM.ORDER_NO%type ,
    MM_ID TREATM_PARAM.MM_ID%type ,
    FROM_DATE TREATM_PARAM.FROM_DATE%type ,
    TREATM_PARAM1_ID TREATM_PARAM.TREATM_PARAM1_ID%type ,
    FIELD_TYPE_ID TREATM_PARAM.FIELD_TYPE_ID%type ,
    CRD TREATM_PARAM.CRD%type ,
    VALUE_TYPE_ID TREATM_PARAM.VALUE_TYPE_ID%type ,
    MDD TREATM_PARAM.MDD%type ,
    TREATM_ID TREATM_PARAM.TREATM_ID%type ,
    VALUE TREATM_PARAM.VALUE%type ,
    ROLL_TYPE TREATM_PARAM.ROLL_TYPE%type ,
    PARAM_TYPE_ID TREATM_PARAM.PARAM_TYPE_ID%type ,
    EPI_ID TREATM_PARAM.EPI_ID%type );
type TREATM_PARAM_tapi_tab
IS
  TABLE OF TREATM_PARAM_tapi_rec;

type TREATM_PARAM_rec
IS
  record
  (
    TREATM_PARAM_ID TREATM_PARAM.TREATM_PARAM_ID%type ,
    UNIT TREATM_PARAM.UNIT%type ,
    SUBJ_ID TREATM_PARAM.SUBJ_ID%type ,
    UNIT_TYPE_ID TREATM_PARAM.UNIT_TYPE_ID%type ,
    DESCRIPTION TREATM_PARAM.DESCRIPTION%type ,
    SUBJ_TYPE_ID TREATM_PARAM.SUBJ_TYPE_ID%type ,
    ORDER_NO TREATM_PARAM.ORDER_NO%type ,
    FROM_DATE TREATM_PARAM.FROM_DATE%type ,
    TREATM_PARAM1_ID TREATM_PARAM.TREATM_PARAM1_ID%type ,
    VALUE_TYPE_ID TREATM_PARAM.VALUE_TYPE_ID%type ,
    TREATM_ID TREATM_PARAM.TREATM_ID%type ,
    VALUE TREATM_PARAM.VALUE%type ,
    ROLL_TYPE TREATM_PARAM.ROLL_TYPE%type ,
    PARAM_TYPE_ID TREATM_PARAM.PARAM_TYPE_ID%type );
type TREATM_PARAM_tapi_tab
IS
  TABLE OF TREATM_PARAM_tapi_rec;





  -- insert
  PROCEDURE ins(
      p_CRU              IN TREATM_PARAM.CRU%type DEFAULT NULL ,
      p_TREATM_PARAM_ID  IN TREATM_PARAM.TREATM_PARAM_ID%type ,
      p_UNIT             IN TREATM_PARAM.UNIT%type DEFAULT NULL ,
      p_TO_DATE          IN TREATM_PARAM.TO_DATE%type ,
      p_SUBJ_ID          IN TREATM_PARAM.SUBJ_ID%type DEFAULT NULL ,
      p_UNIT_TYPE_ID     IN TREATM_PARAM.UNIT_TYPE_ID%type DEFAULT NULL ,
      p_DESCRIPTION      IN TREATM_PARAM.DESCRIPTION%type DEFAULT NULL ,
      p_SUBJ_TYPE_ID     IN TREATM_PARAM.SUBJ_TYPE_ID%type DEFAULT NULL ,
      p_MDU              IN TREATM_PARAM.MDU%type DEFAULT NULL ,
      p_ORDER_NO         IN TREATM_PARAM.ORDER_NO%type DEFAULT NULL ,
      p_MM_ID            IN TREATM_PARAM.MM_ID%type DEFAULT NULL ,
      p_FROM_DATE        IN TREATM_PARAM.FROM_DATE%type ,
      p_TREATM_PARAM1_ID IN TREATM_PARAM.TREATM_PARAM1_ID%type DEFAULT NULL ,
      p_FIELD_TYPE_ID    IN TREATM_PARAM.FIELD_TYPE_ID%type DEFAULT NULL ,
      p_CRD              IN TREATM_PARAM.CRD%type DEFAULT NULL ,
      p_VALUE_TYPE_ID    IN TREATM_PARAM.VALUE_TYPE_ID%type DEFAULT NULL ,
      p_MDD              IN TREATM_PARAM.MDD%type DEFAULT NULL ,
      p_TREATM_ID        IN TREATM_PARAM.TREATM_ID%type ,
      p_VALUE            IN TREATM_PARAM.VALUE%type DEFAULT NULL ,
      p_ROLL_TYPE        IN TREATM_PARAM.ROLL_TYPE%type DEFAULT NULL ,
      p_PARAM_TYPE_ID    IN TREATM_PARAM.PARAM_TYPE_ID%type ,
      p_EPI_ID           IN TREATM_PARAM.EPI_ID%type );
  -- update
  PROCEDURE upd(
      p_CRU              IN TREATM_PARAM.CRU%type DEFAULT NULL ,
      p_TREATM_PARAM_ID  IN TREATM_PARAM.TREATM_PARAM_ID%type ,
      p_UNIT             IN TREATM_PARAM.UNIT%type DEFAULT NULL ,
      p_TO_DATE          IN TREATM_PARAM.TO_DATE%type ,
      p_SUBJ_ID          IN TREATM_PARAM.SUBJ_ID%type DEFAULT NULL ,
      p_UNIT_TYPE_ID     IN TREATM_PARAM.UNIT_TYPE_ID%type DEFAULT NULL ,
      p_DESCRIPTION      IN TREATM_PARAM.DESCRIPTION%type DEFAULT NULL ,
      p_SUBJ_TYPE_ID     IN TREATM_PARAM.SUBJ_TYPE_ID%type DEFAULT NULL ,
      p_MDU              IN TREATM_PARAM.MDU%type DEFAULT NULL ,
      p_ORDER_NO         IN TREATM_PARAM.ORDER_NO%type DEFAULT NULL ,
      p_MM_ID            IN TREATM_PARAM.MM_ID%type DEFAULT NULL ,
      p_FROM_DATE        IN TREATM_PARAM.FROM_DATE%type ,
      p_TREATM_PARAM1_ID IN TREATM_PARAM.TREATM_PARAM1_ID%type DEFAULT NULL ,
      p_FIELD_TYPE_ID    IN TREATM_PARAM.FIELD_TYPE_ID%type DEFAULT NULL ,
      p_CRD              IN TREATM_PARAM.CRD%type DEFAULT NULL ,
      p_VALUE_TYPE_ID    IN TREATM_PARAM.VALUE_TYPE_ID%type DEFAULT NULL ,
      p_MDD              IN TREATM_PARAM.MDD%type DEFAULT NULL ,
      p_TREATM_ID        IN TREATM_PARAM.TREATM_ID%type ,
      p_VALUE            IN TREATM_PARAM.VALUE%type DEFAULT NULL ,
      p_ROLL_TYPE        IN TREATM_PARAM.ROLL_TYPE%type DEFAULT NULL ,
      p_PARAM_TYPE_ID    IN TREATM_PARAM.PARAM_TYPE_ID%type ,
      p_EPI_ID           IN TREATM_PARAM.EPI_ID%type );
  -- delete
  PROCEDURE del(
      p_TREATM_PARAM_ID IN TREATM_PARAM.TREATM_PARAM_ID%type );
END TREATM_PARAM_tapi;

/
