--------------------------------------------------------
--  DDL for Trigger TRG2_DM_MESSAGE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_MESSAGE" 
BEFORE INSERT OR UPDATE ON DM_MESSAGE FOR EACH ROW
BEGIN
  IF INSERTING
  THEN
    IF :new.MESSAGE_ID IS NULL OR :new.MESSAGE_ID = 0
      THEN
      SELECT SEQ_BASE.NEXTVAL
      INTO :NEW.MESSAGE_ID
      FROM DUAL;
      END IF;
      :new.CRD := SYSTIMESTAMP;      --LÉTREHOZÁS IDÕPONTJA 
      :NEW.CRU := NVL(V('APP_USER'), USER); --APEX USER AKI LÉTREHOZZA A REKORDOT
      ELSIF UPDATING
      THEN
      :new.MDD := SYSTIMESTAMP;      --MÓDOSÍTÁS IDÕPONTJA
      :NEW.MDU := NVL(V('APP_USER'), USER); --APEX USER AKI MÓDOSÍT
      END IF;
      END TRG_DM_MESSAGE;
/
ALTER TRIGGER "TRG2_DM_MESSAGE" ENABLE;
