--------------------------------------------------------
--  DDL for Trigger TRG2_ALERT_PARAM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_ALERT_PARAM" 
BEFORE INSERT OR UPDATE ON ALERT_PARAM FOR EACH ROW
BEGIN
  IF INSERTING
  THEN
    IF :new.ALERT_PARAM_ID IS NULL OR :new.ALERT_PARAM_ID = 0
      THEN
      SELECT SEQ_BASE.NEXTVAL
      INTO :NEW.ALERT_PARAM_ID
      FROM DUAL;
      END IF;
      :new.CRD := SYSTIMESTAMP;      --LÉTREHOZÁS IDÕPONTJA 
      :NEW.CRU := NVL(V('APP_USER'), USER); --APEX USER AKI LÉTREHOZZA A REKORDOT
      ELSIF UPDATING
      THEN
      :new.MDD := SYSTIMESTAMP;      --MÓDOSÍTÁS IDÕPONTJA
      :NEW.MDU := NVL(V('APP_USER'), USER); --APEX USER AKI MÓDOSÍT
      END IF;
      END TRG_ALERT_PARAM;
/
ALTER TRIGGER "TRG2_ALERT_PARAM" ENABLE;
