--------------------------------------------------------
--  DDL for Trigger TRG2_DM_ANALYSIS_MET
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_ANALYSIS_MET" 
BEFORE INSERT OR UPDATE ON DM_ANALYSIS_MET FOR EACH ROW
BEGIN
  IF INSERTING
  THEN
    IF :new.ANALYSIS_MET_ID IS NULL OR :new.ANALYSIS_MET_ID = 0
      THEN
      SELECT SEQ_BASE.NEXTVAL
      INTO :NEW.ANALYSIS_MET_ID
      FROM DUAL;
      END IF;
      :new.CRD := SYSTIMESTAMP;      --LÉTREHOZÁS IDÕPONTJA 
      :NEW.CRU := NVL(V('APP_USER'), USER); --APEX USER AKI LÉTREHOZZA A REKORDOT
      ELSIF UPDATING
      THEN
      :new.MDD := SYSTIMESTAMP;      --MÓDOSÍTÁS IDÕPONTJA
      :NEW.MDU := NVL(V('APP_USER'), USER); --APEX USER AKI MÓDOSÍT
      END IF;
      END TRG_DM_ANALYSIS_MET;
/
ALTER TRIGGER "TRG2_DM_ANALYSIS_MET" ENABLE;
