--------------------------------------------------------
--  DDL for Trigger TRG2_DM_CAT_USAGE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_CAT_USAGE" 
BEFORE INSERT OR UPDATE ON DM_CAT_USAGE FOR EACH ROW
BEGIN
  IF INSERTING
  THEN
    IF :new.CAT_USAGE_ID IS NULL OR :new.CAT_USAGE_ID = 0
      THEN
      SELECT SEQ_BASE.NEXTVAL
      INTO :NEW.CAT_USAGE_ID
      FROM DUAL;
      END IF;
      :new.CRD := SYSTIMESTAMP;      --LÉTREHOZÁS IDÕPONTJA 
      :NEW.CRU := NVL(V('APP_USER'), USER); --APEX USER AKI LÉTREHOZZA A REKORDOT
      ELSIF UPDATING
      THEN
      :new.MDD := SYSTIMESTAMP;      --MÓDOSÍTÁS IDÕPONTJA
      :NEW.MDU := NVL(V('APP_USER'), USER); --APEX USER AKI MÓDOSÍT
      END IF;
      END TRG_DM_CAT_USAGE;
/
ALTER TRIGGER "TRG2_DM_CAT_USAGE" ENABLE;
