--------------------------------------------------------
--  DDL for Trigger TRG2_DM_CURRENCY_CHANGE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_CURRENCY_CHANGE" 
BEFORE INSERT OR UPDATE ON DM_CURRENCY_CHANGE FOR EACH ROW
BEGIN
  IF INSERTING
  THEN
    IF :new.CURR_CHANG_ID IS NULL OR :new.CURR_CHANG_ID = 0
      THEN
      SELECT SEQ_BASE.NEXTVAL
      INTO :NEW.CURR_CHANG_ID
      FROM DUAL;
      END IF;
      :new.CRD := SYSTIMESTAMP;      --LÉTREHOZÁS IDÕPONTJA 
      :NEW.CRU := NVL(V('APP_USER'), USER); --APEX USER AKI LÉTREHOZZA A REKORDOT
      ELSIF UPDATING
      THEN
      :new.MDD := SYSTIMESTAMP;      --MÓDOSÍTÁS IDÕPONTJA
      :NEW.MDU := NVL(V('APP_USER'), USER); --APEX USER AKI MÓDOSÍT
      END IF;
      END TRG_DM_CURRENCY_CHANGE;
/
ALTER TRIGGER "TRG2_DM_CURRENCY_CHANGE" ENABLE;
