--------------------------------------------------------
--  DDL for Trigger TRG2_CELL_COMMENTS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_CELL_COMMENTS" 
BEFORE INSERT OR UPDATE ON CELL_COMMENTS FOR EACH ROW
BEGIN
  IF INSERTING
  THEN
    IF :new.CELL_COMMETNT_ID IS NULL OR :new.CELL_COMMETNT_ID = 0
      THEN
      SELECT SEQ_BASE.NEXTVAL
      INTO :NEW.CELL_COMMETNT_ID
      FROM DUAL;
      END IF;
      :new.CRD := SYSTIMESTAMP;      --LÉTREHOZÁS IDÕPONTJA 
      :NEW.CRU := NVL(V('APP_USER'), USER); --APEX USER AKI LÉTREHOZZA A REKORDOT
      ELSIF UPDATING
      THEN
      :new.MDD := SYSTIMESTAMP;      --MÓDOSÍTÁS IDÕPONTJA
      :NEW.MDU := NVL(V('APP_USER'), USER); --APEX USER AKI MÓDOSÍT
      END IF;
      END TRG_CELL_COMMENTS;
/
ALTER TRIGGER "TRG2_CELL_COMMENTS" ENABLE;
