REM INSERTING into V_ADDRESS_SPLITTEER
SET DEFINE OFF;
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest Október huszonharmadika utca 8-10. II em.','1117 ','utca ','Budapest','Október huszonharmadika');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2200 Monor, Móricz Zsigmond út 29.','2200 ','út ','Monor','Móricz Zsigmond');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1037 Budapest, Bóbita utca 4A 1 9','1037 ','utca ','Budapest','Bóbita');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1145 Budapest, Törökör u. 2','1145 ','u.','Budapest','Törökör');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest Bogdánfy utca 71c','1117 ','utca ','Budapest','Bogdánfy');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('6724 Szeged, Rókusi krt. 20.','6724 ','krt.','Szeged','Rókusi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1066 Budapest, Nyugati tér 1.','1066 ','tér ','Budapest','Nyugati');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1132 Budapest, Kádár u. 6.','1132 ','u.','Budapest','Kádár');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1134. Budapest, Szabolcs u. 30.','1134.','u.','Budapest','Szabolcs');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Kende u. 16.','1117 ','u.','Budapest','Kende');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1213 Budapest, Mátra u. 6.','1213 ','u.','Budapest','Mátra');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2364 Ócsa, Bajcsy-Zs. u. 99.','2364 ','u.','Ócsa','Bajcsy-Zs.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1116 Budapest, Nándorfejérvári út 36.','1116 ','út ','Budapest','Nándorfejérvári');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1118 Budapest, Rétköz u. 3.','1118 ','u.','Budapest','Rétköz');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('CA 94043 Mountain View, 1600 Amphitheatre Pkwy',null,null,'CA 94043 Mountain',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1149 Budapest, Angol utca 34','1149 ','utca ','Budapest','Angol');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1016 Budapest , Aladár u. 4/b. 1em. 3.','1016 ','u.','Budapest',', Aladár');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1139 Budapest, Váci út 99.','1139 ','út ','Budapest','Váci');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Váli u. 2.','1117 ','u.','Budapest','Váli');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1202 Budapest, Jókai Mór u. 82.','1202 ','u.','Budapest','Jókai Mór');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1097 Budapest, Könyves Kálmán Krt. 12-14.','1097 ','Krt.','Budapest','Könyves Kálmán');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1132 Budapest, Váci út 20-26.','1132 ','út ','Budapest','Váci');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('9022 Gyõr, Szent István u. 10/a','9022 ','u.','Gyõr','Szent István');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2013 Pomáz, Ibolya u. 5.','2013 ','u.','Pomáz','Ibolya');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1112 Budapest, Menyecske u 11. 9. em. 56.','1112 ','u ','Budapest','Menyecske');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1056 Budapest, Szerb u. 21-23.','1056 ','u.','Budapest','Szerb');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1012 Budapest, Vérmezõ út 4.','1012 ','út ','Budapest','Vérmezõ');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2030 Érd, Radnai u. 72.','2030 ','u.','Érd','Radnai');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1152 Budapest, Szentmihályi út 171 III 3.12.','1152 ','út ','Budapest','Szentmihályi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1063 Budapest, Szív utca 33','1063 ','utca ','Budapest','Szív');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1053 Budapest, Egyetem tér 1-3.','1053 ','tér ','Budapest','Egyetem');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1111 Budapest, Karinthy F. út 23.111./13','1111 ','út ','Budapest','Karinthy F.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Karinthy F. út 15.','1117 ','út ','Budapest','Karinthy F.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2030 Érd, Diósdi út 18','2030 ','út ','Érd','Diósdi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1143 Budapest, Stefánia út 51.','1143 ','út ','Budapest','Stefánia');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('4400 Nyíregyháza, Kálvin tér 8.','4400 ','tér ','Nyíregyháza','Kálvin');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1114 Budapest, Bukarest utca 13. 3. em. 15','1114 ','utca ','Budapest','Bukarest');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Pázmány Péter sétány 1/A','1117 ','sétány ','Budapest','Pázmány Péter');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1031 Budapest, Torma Károly u. 3. II. em. 7','1031 ','u.','Budapest','Torma Károly');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('Adam House, 7 Adam Street, The Strand, London WC2N 6AA, UK',null,null,'Adam',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1051 Budapest. Sas u. 10-12.','1051 ','u.','Budapest','Sas');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2000 Szentendre, Kálvária út 65.','2000 ','út ','Szentendre','Kálvária');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1143 Budapest, Francia út 40/b.','1143 ','út ','Budapest','Francia');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('6000 Kecskemét, Homokszem utca 3-5.','6000 ','utca ','Kecskemét','Homokszem');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2225 Üllõ, Pesti út 284.','2225 ','út ','Üllõ','Pesti');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2200 Monor, Petõfi u. 16.','2200 ','u.','Monor','Petõfi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Bercsényi u. 34/B.','1117 ','u.','Budapest','Bercsényi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1037 Budapest, Bóbita utca 4A 1 9','1037 ','utca ','Budapest','Bóbita');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values (null,null,null,null,null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2040 Budaörs, Sport u. 2-4.','2040 ','u.','Budaörs','Sport');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2041 Budaörs, Budapark Keleti 3.','2041 ',null,'Budaörs',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1139 Budapest, Forgách u. 9/B.','1139 ','u.','Budapest','Forgách');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2260 Gyál, Bercsényi u. 6.','2260 ','u.','Gyál','Bercsényi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Október 23. u. 8-10.','1117 ','u.','Budapest','Október 23.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2040 Budaörs, Petõfi Sándor u. 64.','2040 ','u.','Budaörs','Petõfi Sándor');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1106 Budapest, Örs vezér tere 25. ','1106 ',null,'Budapest',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2051 Biatorbágy, Juhász Gyula u. 26.','2051 ','u.','Biatorbágy','Juhász Gyula');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('8274 Köveskál, Iskola u. 4.','8274 ','u.','Köveskál','Iskola');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1138 Budapest Dunavirág utca 2.','1138 ','utca ','Budapest','Dunavirág');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1118 Budapest, Ménesi út 100./Nagy Lajos K. ú. 40.','1118 ','út ','Budapest','Ménesi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('Vukovarska 58, 51000 RIJEKA, CROATIA',null,null,'Vukovarska',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('Popradská 68 04011 Kosice Slovensko',null,null,'Popradská',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1132 Budapest, Váci út 36-38.','1132 ','út ','Budapest','Váci');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('6600 Szentes, József Attila u. 8. III./7.','6600 ','u.','Szentes','József Attila');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('40210 Düsseldorf BismarckstraBe 93.',null,null,'Düsseldorf',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('6720 Szeged, Dugonics tér 13.','6720 ','tér ','Szeged','Dugonics');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Bercsényi u. 32/b.','1117 ','u.','Budapest','Bercsényi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1075 Budapest, Rumbach Sebestyén u. 19-21.','1075 ','u.','Budapest','Rumbach Sebestyén');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1051 Budapest, Andrássy út 12.','1051 ','út ','Budapest','Andrássy');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1096 Budapest, Lechner Odön fasor 6.','1096 ','fasor ','Budapest','Lechner Odön');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2030 Érd, Diósdi út 18.','2030 ','út ','Érd','Diósdi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Hauszmann Alajos u. 4. ','1117 ','u.','Budapest','Hauszmann Alajos');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1117 Budapest, Karínthy F. út 17.','1117 ','út ','Budapest','Karínthy F.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1135 Budapest, Jász utca 71.','1135 ','utca ','Budapest','Jász');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1211 Budapest, II. Rákóczi F. u. 50-56. X/128.','1211 ','u.','Budapest','II. Rákóczi F.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('3300 Eger, Leányka u. 4.','3300 ','u.','Eger','Leányka');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2185 Váckisújfalu, Õsz u. 8.','2185 ','u.','Váckisújfalu','Õsz');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1112 Budapest, Menyecske utca 11.','1112 ','utca ','Budapest','Menyecske');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2185 Váckisújfalu, Õsz u. 8.','2185 ','u.','Váckisújfalu','Õsz');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('21000 NOVI SAD, Strazilovska 16. Republika Srbija',null,null,'NOVI',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1091 Budapest, Üllõi út 131.','1091 ','út ','Budapest','Üllõi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1146 Budapest, Hermina út 17.','1146 ','út ','Budapest','Hermina');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1174 Budapest, Ady E. u. 50.','1174 ','u.','Budapest','Ady E.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1111 Budapest, Karinthy F. út 23.111./13','1111 ','út ','Budapest','Karinthy F.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('Postbus 9010, 6500 GL NIJMEGEN, The Netherlands',null,null,'Postbus',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('9700 Szombathely, Százhold u.20.','9700 ','u.','Szombathely','Százhold');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1054 Budapest, Szemere u. 19. I/2B.','1054 ','u.','Budapest','Szemere');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2220 Vecsés, Achim András utca 23.','2220 ','utca ','Vecsés','Achim András');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1034 Budapest, lll. kerület, Zápor utca 12./B. 1/3.','1034 ','utca ','Budapest','lll. kerület, Zápor');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1137 Budapest, Radnóti Miklós utca 2.','1137 ','utca ','Budapest','Radnóti Miklós');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1149 Budapest, Mogyoródi út 53.','1149 ','út ','Budapest','Mogyoródi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1054 Budapest, Hold u. 7.','1054 ','u.','Budapest','Hold');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1084 Budapest, Tolnai L. u. 4','1084 ','u.','Budapest','Tolnai L.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1123 Budapest, Alkotás u. 31. I/1.','1123 ','u.','Budapest','Alkotás');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1118 Budapest, Pannonhalmi út 52.','1118 ','út ','Budapest','Pannonhalmi');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1036 Budapest, Galagonya u. 5. ','1036 ','u.','Budapest','Galagonya');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('2364 Ócsa, Gábor Áron u 7.','2364 ','u ','Ócsa','Gábor Áron');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1121 Budapest, Konkoly-Thege M. u. 29-33.','1121 ','u.','Budapest','Konkoly-Thege M.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1148 Budapest, Nagy Lajos király útja 1-9.','1148 ','útja ','Budapest','Nagy Lajos király');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1111 Budapest, Mûegyetem rkp. 3-9.','1111 ',null,'Budapest',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1022 Budapest, Lóczy L. u. 11.','1022 ','u.','Budapest','Lóczy L.');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1138 Budapest, Váci út 141.','1138 ','út ','Budapest','Váci');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1096 Budapest, Telepy u. 24.','1096 ','u.','Budapest','Telepy');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1031 Budapest, Záhony u. 7.','1031 ','u.','Budapest','Záhony');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1067 Budapest, Teréz krt. 31.','1067 ','krt.','Budapest','Teréz');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1239 Budapest, Bevásárló u. 2.','1239 ','u.','Budapest','Bevásárló');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1148 Budapest Nagy Lajos király útja 40.','1148 ','útja ','Budapest','Nagy Lajos király');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1095 Budapest, Lechner Ödön fasor 8.','1095 ','fasor ','Budapest','Lechner Ödön');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1097 Budapest, Könyves Kálmán krt. 11. B building','1097 ','krt.','Budapest','Könyves Kálmán');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('A-8042 Graz, Gluckgasse 17.',null,null,'A-8042 Graz',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1084 Budapest, Õr utca 5-7.','1084 ','utca ','Budapest','Õr');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1039 Budapest, Csobánka tér 7.','1039 ','tér ','Budapest','Csobánka');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1142 Budapest, Rákospatak u. 79/B.','1142 ','u.','Budapest','Rákospatak');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1138 Budapest Dunavirág utca 2.','1138 ','utca ','Budapest','Dunavirág');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1095 Budapest, Mester u. 21.','1095 ','u.','Budapest','Mester');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1093 Budapest, Lónyay utca 31','1093 ','utca ','Budapest','Lónyay');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('SK 821 08 Bratislava, Záhradnícka 72. Slovakia',null,null,'SK',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1055 Budapest, Szalay u. 16.','1055 ','u.','Budapest','Szalay');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1012 WX Amsterdam, Spui 21, The Netherlands','1012 ',null,'WX',null);
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1116 Budapest, Bükköny u. 2-4.','1116 ','u.','Budapest','Bükköny');
Insert into V_ADDRESS_SPLITTEER (VALUE,ZIP,PLACE_TYPE,CITY,STREET) values ('1039 Budapest, Czetz János u. 48-50.','1039 ','u.','Budapest','Czetz János');
