--------------------------------------------------------
--  DDL for View V_DM_XL_REL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_DM_XL_REL" ("DM_XL_REL_ID", "DM_XL_ID1", "PARAM_TYPE_ID1", "ORDER_NO1", "LIST_TYPE_ID1", "DM_XL_ID2", "PARAM_TYPE_ID2", "ORDER_NO2", "LIST_TYPE_ID2", "DM_XL_ID3", "PARAM_TYPE_ID3", "ORDER_NO3", "LIST_TYPE_ID3", "REL_TYPE_ID", "W_REL_TYPE_NAME", "MATHOP", "CONNUM", "FROM_DATE", "TO_DATE") AS 
  SELECT
    DXR.DM_XL_REL_ID
  , DXR.DM_XL_ID1
  , (SELECT PARAM_TYPE_ID FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID1) PARAM_TYPE_ID1
  , (SELECT ORDER_NO FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID1) ORDER_NO1
  , (SELECT DX.LIST_TYPE_ID FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID1) LIST_TYPE_ID1
  , DXR.DM_XL_ID2
  , (SELECT PARAM_TYPE_ID FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID2)PARAM_TYPE_ID2
  , (SELECT ORDER_NO FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID2) ORDER_NO2
  , (SELECT DX.LIST_TYPE_ID FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID2) LIST_TYPE_ID2
  , DXR.DM_XL_ID3
  , (SELECT PARAM_TYPE_ID FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID3) PARAM_TYPE_ID3
  , (SELECT ORDER_NO FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID3) ORDER_NO3
  , (SELECT DX.LIST_TYPE_ID FROM DM_XL DX WHERE DX.DM_XL_ID = DXR.DM_XL_ID3) LIST_TYPE_ID3
  , DXR.REL_TYPE_ID
  , DXR.W_REL_TYPE_NAME
  , DXR.MATHOP
  , DXR.CONNUM
  , DXR.FROM_DATE
  , DXR.TO_DATE
  FROM
  DM_XL_REL DXR;
