--------------------------------------------------------
--  DDL for View V_DM_ROLE
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_DM_ROLE" ("ROLE_USER_ID", "USER_ID", "ROLE_ID", "USER_SUBJ_ID", "USER_NAME", "DESCRIPTION", "ORG_ID", "ORG_NAME", "DATA_OWNER_ID", "ROLE_NAME", "SUPER_TYP_ID") AS 
  SELECT 
  DM_ROLE_USER.ROLE_USER_ID, 
  DM_ROLE_USER.USER_ID, 
  DM_ROLE_USER.ROLE_ID, 
  DM_USER.SUBJ_ID USER_SUBJ_ID, 
  DM_USER.USER_NAME, 
  DM_USER.DESCRIPTION, 
  --SUBJECT.SUBJ_NAME ORG_NAME, 
  --SUBJECT.SUBJ_ID ORG_ID, 
  DM_ROLE_USER.SUBJ_ID ORG_ID,
  lookup_subj_name(DM_ROLE_USER.SUBJ_ID) ORG_NAME,
  DM_ROLE_USER.DATA_OWNER_ID, 
  DM_ROLE.ROLE_NAME,
  --(SELECT SUPER_TYP_ID FROM vk_pf_dm_role_super_typ T WHERE t.ROLE_ID = DM_ROLE_USER.ROLE_ID) SUPER_TYP_ID
  null SUPER_TYP_ID
FROM
  DM_ROLE_USER
Inner Join DM_ROLE ON 
  DM_ROLE_USER.ROLE_ID = DM_ROLE.ROLE_ID
Inner Join DM_USER ON 
  DM_ROLE_USER.USER_ID = DM_USER.USER_ID
Inner Join SUBJECT ON 
  DM_ROLE_USER.DATA_OWNER_ID = SUBJECT.SUBJ_ID;
