--------------------------------------------------------
--  DDL for View V_INVENT_EPISODES
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_INVENT_EPISODES" ("EPI_ID", "PREV_EPI_ID", "EPI_NAME", "EPI_TYPE_ID", "EPI_TYPE_NAME", "EPI_VALUE_TYPE_ID", "VALUE_TYPE_NAME", "EPI_VALUE", "EPI_UNIT", "EPI_UNIT_TYPE_ID", "EPI_DESCRIPTION", "PARAM_CNT", "EPI_SUBJ_ID", "EPI_SUBJ_NAME", "SUBJ_ID", "PARAM_TYPE_ID", "PARAM_TYPE_NAME", "VALUE_TYPE_ID", "PARAM_VALUE_TYPE_NAME", "PARAM_VALUE", "PARAM_UNIT", "PARAM_DESCRIPTION", "MM_ID", "MM_SUBJ_ID", "MM_SUBJ_NAME", "MM_TYPE_ID", "FILE_NAME", "MM_BLOB", "TITLE", "URL_FOR_JS", "CRU", "CRD", "MDU", "MDD") AS 
  SELECT 
    EPI.EPI_ID, 
    (SELECT 
        EPI_ID2 
    FROM 
        EPI_REL 
    where 
        EPI_ID1 = EPI.EPI_ID) AS PREV_EPI_ID, 
    EPI.EPI_NAME, 
    EPI.EPI_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(EPI.EPI_TYPE_ID) EPI_TYPE_NAME, 
    EPI.VALUE_TYPE_ID EPI_VALUE_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(EPI.VALUE_TYPE_ID) VALUE_TYPE_NAME, 
    EPI.EPI_VALUE, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(EPI.EPI_UNIT_TYPE_ID) EPI_UNIT, 
    EPI.EPI_UNIT_TYPE_ID, 
    EPI.DESCRIPTION EPI_DESCRIPTION, 
   -- EPI.STAT_TYPE_ID STAT_TYPE_ID, 
    (SELECT 
        COUNT(1) 
    FROM 
        EPI_SUBJ_PARAM 
    WHERE 
        EPI_SUBJ_PARAM.EPI_ID = EPI_ID) param_cnt, 
    EPI_SUBJ_PARAM.EPI_SUBJ_ID, 
    base_PKG.SUBJECTIV_NAME_F(EPI_SUBJ_PARAM.SUBJ_ID) EPI_SUBJ_NAME, 
    EPI_SUBJ_PARAM.SUBJ_ID, 
    EPI_SUBJ_PARAM.PARAM_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(EPI_SUBJ_PARAM.PARAM_TYPE_ID) PARAM_TYPE_NAME, 
    EPI_SUBJ_PARAM.VALUE_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(EPI.VALUE_TYPE_ID) PARAM_VALUE_TYPE_NAME, 
    EPI_SUBJ_PARAM.VALUE PARAM_VALUE, 
    EPI_SUBJ_PARAM.UNIT PARAM_UNIT, 
    EPI_SUBJ_PARAM.DESCRIPTION PARAM_DESCRIPTION, 
    EPI_SUBJ_PARAM.MM_ID, 
    MM_FILES.SUBJ_ID MM_SUBJ_ID, 
    base_PKG.SUBJECTIV_NAME_F(MM_FILES.SUBJ_ID) MM_SUBJ_NAME, 
    MM_FILES.MM_TYPE_ID, 
    MM_FILES.FILE_NAME, 
    MM_FILES.MM_BLOB, 
    MM_FILES.TITLE, 
    APEX_UTIL.PREPARE_URL('f?p=:4041:::NO:4041:P4041_MM_ID:' || MM_FILES.MM_ID, NULL, 3) AS URL_FOR_JS, 
    EPI.CRU, 
    EPI.CRD, 
    EPI.MDU, 
    EPI.MDD 
FROM 
    EPI, 
    EPI_SUBJ_PARAM, 
    MM_FILES 
WHERE 
    EPI.EPI_ID = EPI_SUBJ_PARAM.EPI_ID(+) AND (EPI_SUBJ_PARAM.ORDER_NO = 1 OR EPI_SUBJ_PARAM.ORDER_NO IS NULL) AND EPI_SUBJ_PARAM.MM_ID = MM_FILES.MM_ID(+);
