--------------------------------------------------------
--  DDL for View V_INVENT_INVENT_PARAM
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_INVENT_INVENT_PARAM" ("INVENT_ID", "SUBJ_NAME", "INVENT_TYPE_ID", "INVENT_TYPE_NAME", "INVENT_VALUE", "ORDER_VALUE", "RESERV_VALUE", "DESCRIPTION", "INVENT_NAME", "ORDER_NO", "INVENT_PARAM_INVENT_ID", "INVENT_PARAM_ID", "PARAM_TYPE_ID", "PARAM_TYPE_NAME", "VALUE_TYPE_ID", "PARAM_VALUE_TYPE_NAME", "VALUE", "UNIT", "SUBJ1_ID", "ATADO", "SUBJ2_ID", "ATVEVO", "EPI_ID", "EPI_TYPE_NAME", "PREV_EPI_ID", "PARAM_DESCRIPTION", "MM_ID", "FILE_NAME", "MM_BLOB", "MM_FILES", "MM_TYPE_NAME", "MM_CHARSET") AS 
  select 
INVENT.INVENT_ID as INVENT_ID,
BASE_PKG.SUBJECTIV_NAME_F(INVENT.SUBJ_ID) as SUBJ_NAME,
INVENT.INVENT_TYPE_ID as INVENT_TYPE_ID,
PKG_INVENT.LOOKUP_SUPER_TYP_NAME(INVENT.INVENT_TYPE_ID) as INVENT_TYPE_NAME,
INVENT.INVENT_VALUE as INVENT_VALUE,
INVENT.ORDER_VALUE as ORDER_VALUE,
INVENT.RESERV_VALUE as RESERV_VALUE,
INVENT.DESCRIPTION as DESCRIPTION,
INVENT.INVENT_NAME as INVENT_NAME,
INVENT_PARAM.ORDER_NO as ORDER_NO,
INVENT_PARAM.INVENT_ID as INVENT_PARAM_INVENT_ID,
INVENT_PARAM.INVENT_PARAM_ID as INVENT_PARAM_ID,
INVENT_PARAM.PARAM_TYPE_ID as PARAM_TYPE_ID,
PKG_INVENT.LOOKUP_SUPER_TYP_NAME(INVENT_PARAM.PARAM_TYPE_ID) as PARAM_TYPE_NAME,
INVENT_PARAM.VALUE_TYPE_ID as VALUE_TYPE_ID,
PKG_INVENT.LOOKUP_SUPER_TYP_NAME(INVENT_PARAM.VALUE_TYPE_ID) as PARAM_VALUE_TYPE_NAME,
INVENT_PARAM.value as value,
INVENT_PARAM.UNIT as UNIT,
INVENT_PARAM.SUBJ1_ID as SUBJ1_ID,
BASE_PKG.SUBJECTIV_NAME_F(INVENT_PARAM.SUBJ1_ID) as ATADO,
INVENT_PARAM.SUBJ2_ID as SUBJ2_ID,
BASE_PKG.SUBJECTIV_NAME_F(INVENT_PARAM.SUBJ2_ID) as ATVEVO,
INVENT_PARAM.EPI_ID as EPI_ID,
PKG_INVENT.LOOKUP_EPI_SUPER_TYP_NAME(INVENT_PARAM.EPI_ID) as EPI_TYPE_NAME,
(select EPI_ID2 from EPI_REL where EPI_ID1 = INVENT_PARAM.EPI_ID) as PREV_EPI_ID,
INVENT_PARAM.DESCRIPTION as PARAM_DESCRIPTION,
INVENT_PARAM.MM_ID as MM_ID,
MM_FILES.FILE_NAME as FILE_NAME,
MM_FILES.MM_BLOB as MM_BLOB,
MM_FILES.MAIN_TYPE as MM_FILES,
PKG_INVENT.LOOKUP_SUPER_TYP_NAME(MM_FILES.MM_TYPE_ID)  as MM_TYPE_NAME,
MM_FILES.MM_CHARSET as MM_CHARSET
from 
INVENT, INVENT_PARAM, MM_FILES
where
    INVENT.INVENT_ID = INVENT_PARAM.INVENT_ID
and INVENT_PARAM.MM_ID = MM_FILES.MM_ID(+);
