REM INSERTING into V_INTERVALL
SET DEFINE OFF;
Insert into V_INTERVALL (INTERVALL_ID,INTERVALL_TEXT,PARAM_FDATE,PARAM_TDATE) values ('1','-',null,null);
Insert into V_INTERVALL (INTERVALL_ID,INTERVALL_TEXT,PARAM_FDATE,PARAM_TDATE) values ('2','2015.05.22-2099.12.31',to_date('15-MÁJ.  -22','RR-MON-DD'),to_date('99-DEC.  -31','RR-MON-DD'));
