--------------------------------------------------------
--  DDL for View V_INVENT_PARAM
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_INVENT_PARAM" ("INVENT_ID", "ORDER_NO", "INVENT_PARAM_ID", "PARAM_TYPE_ID", "PARAM_TYPE_NAME", "VALUE_TYPE_ID", "VALUE_TYPE_NAME", "VALUE", "UNIT", "SUBJ1_ID", "ATADO", "SUBJ2_ID", "ATVEVO", "EPI_ID", "EPI_TYPE_NAME", "DESCRIPTION", "MM_ID", "MM_TYPE_ID", "MM_TYPE_NAME", "FILE_NAME", "MM_BLOB", "CRU", "CRD", "MDU", "MDD") AS 
  SELECT 
    INVENT_PARAM.INVENT_ID, 
    INVENT_PARAM.ORDER_NO, 
    INVENT_PARAM.INVENT_PARAM_ID, 
    INVENT_PARAM.PARAM_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(INVENT_PARAM.PARAM_TYPE_ID) PARAM_TYPE_NAME, 
    INVENT_PARAM.VALUE_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(INVENT_PARAM.VALUE_TYPE_ID) VALUE_TYPE_NAME, 
    INVENT_PARAM.VALUE, 
    INVENT_PARAM.UNIT, 
    INVENT_PARAM.SUBJ1_ID, 
    BASE_PKG.SUBJECTIV_NAME_F(INVENT_PARAM.SUBJ1_ID) ATADO, 
    INVENT_PARAM.SUBJ2_ID, 
    BASE_PKG.SUBJECTIV_NAME_F(INVENT_PARAM.SUBJ2_ID) ATVEVO, 
    INVENT_PARAM.EPI_ID, 
    PKG_INVENT.LOOKUP_EPI_SUPER_TYP_NAME(INVENT_PARAM.EPI_ID) EPI_TYPE_NAME, 
    INVENT_PARAM.DESCRIPTION, 
    --INVENT_PARAM.STAT_TYPE_ID, 
    INVENT_PARAM.MM_ID, 
    MM_FILES.MM_TYPE_ID, 
    PKG_INVENT.LOOKUP_MM_SUPER_TYP_NAME(MM_FILES.MM_TYPE_ID) MM_TYPE_NAME, 
    MM_FILES.FILE_NAME, 
    MM_FILES.MM_BLOB, 
    INVENT_PARAM.CRU, 
    INVENT_PARAM.CRD, 
    INVENT_PARAM.MDU, 
    INVENT_PARAM.MDD 
FROM 
    INVENT_PARAM, 
    MM_FILES 
WHERE 
    INVENT_PARAM.MM_ID = MM_FILES.MM_ID(+);
