--------------------------------------------------------
--  DDL for View V_LIST_EPI_SUBJ_PARAM
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_LIST_EPI_SUBJ_PARAM" ("EPI_SUBJ_ID", "SUBJ_ID", "SUBJ_NAME", "EPI_ID", "PARAM_TYPE_ID", "PARAM_TYPE_NAME", "VALUE", "UNIT_TYPE_ID", "UNIT_TYPE_NAME", "DESCRIPTION", "CRU", "CRD", "MDU", "MDD", "MM_ID", "VALUE_TYPE_ID", "VALUE_TYPE_NAME", "ORDER_NO", "UNIT", "FROM_CODE", "GIS_ID") AS 
  SELECT 
    EPI_SUBJ_ID, 
    SUBJ_ID, 
    BASE_PKG.SUBJECTIV_NAME_F(SUBJ_ID) as SUBJ_NAME,
    EPI_ID, 
    PARAM_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(PARAM_TYPE_ID) as PARAM_TYPE_NAME,
    VALUE, 
    UNIT_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(UNIT_TYPE_ID) as UNIT_TYPE_NAME,
    DESCRIPTION, 
   -- STAT_TYPE_ID, 
    CRU, 
    CRD, 
    MDU, 
    MDD, 
    MM_ID, 
    VALUE_TYPE_ID, 
    PKG_INVENT.LOOKUP_SUPER_TYP_NAME(VALUE_TYPE_ID) as VALUE_TYPE_NAME,
    ORDER_NO, 
    UNIT, 
    FROM_CODE, 
    GIS_ID 
FROM 
    EPI_SUBJ_PARAM;
