--------------------------------------------------------
--  DDL for View V_MENU
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_MENU" ("MENU_ITEM_ID", "MENU_ITEM_NAME", "DISPLAY_NAME", "GROUP_ID", "APEX_VARIABLE", "CONTROL_ITEM_ID", "CONTROL_ITEM_NAME", "ASSIGNED_ROLE_ID", "ASSIGNED_ROLE_NAME") AS 
  select  
MENU_ITEMS.MENU_ITEM_ID MENU_ITEM_ID,
MENU_ITEMS.MENU_ITEM_NAME MENU_ITEM_NAME,
substr(MENU_ITEMS.MENU_ITEM_NAME,3)  DISPLAY_NAME ,
(select GROUP_ID from DM_SUPER_TYP where DM_SUPER_TYP.SUPER_TYP_ID = MENU_ITEMS.MENU_ITEM_ID) GROUP_ID,
--(select APEX_VARIABLE from DM_SUPER_TYP where DM_SUPER_TYP.SUPER_TYP_ID = MENU_ITEMS.MENU_ITEM_ID) APEX_VARIABLE,
NULL APEX_VARIABLE,
MENU_ITEMS.CONTROL_ITEM_ID CONTROL_ITEM_ID,
MENU_ITEMS.CONTROL_ITEM_NAME CONTROL_ITEM_NAME,
RIGTHS.ASSIGNED_ROLE_ID ASSIGNED_ROLE_ID,
RIGTHS.ASSIGNED_ROLE_NAME
from
V_MENU_1007 MENU_ITEMS,
V_MENU_1012 RIGTHS
where 
MENU_ITEMS.MENU_ITEM_ID = RIGTHS.MENU_ITEM_ID
union
select 
TO_CHAR(SUPER_TYP_ID) MENU_ITEM_ID,
SUPER_TYPE_NAME MENU_ITEM_NAME,
substr(SUPER_TYPE_NAME,3)  DISPLAY_NAME ,
GROUP_ID GROUP_ID,
null APEX_VARIABLE,
null CONTROL_ITEM_ID,
null CONTROL_ITEM_NAME,
null ASSIGNED_ROLE_ID,
null ASSIGNED_ROLE_NAME
from DM_SUPER_TYP
where SUPER_TYP_ID in (999,998)
order by MENU_ITEM_NAME;
