REM INSERTING into V_ORGANIZATIONS
SET DEFINE OFF;
Insert into V_ORGANIZATIONS (SUBJ_ID,FROM_DATE,TO_DATE,SUBJ_CATEGORY_ID,SUBJ_NAME) values ('1308590112',to_date('15-ÁPR.  -12','RR-MON-DD'),to_date('99-DEC.  -31','RR-MON-DD'),'103','Rendelõintézet');
Insert into V_ORGANIZATIONS (SUBJ_ID,FROM_DATE,TO_DATE,SUBJ_CATEGORY_ID,SUBJ_NAME) values ('1308590167',to_date('15-ÁPR.  -12','RR-MON-DD'),to_date('99-DEC.  -31','RR-MON-DD'),'103','3-as fogorvosi rendelõ');
