--------------------------------------------------------
--  DDL for View V_SUBJ_PARAM
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_SUBJ_PARAM" ("SUBJ_PARAM_ID", "SUBJ_ID", "EPI_ID", "PARAM_TYPE_ID", "PARAM_TYPE_NAME", "VALUE", "UNIT_TYPE_ID", "UNIT_TYPE_NAME", "DESCRIPTION", "STAT_TYPE_ID", "STAT_TYPE_NAME", "CRU", "CRD", "MDU", "MDD", "MM_ID", "VALUE_TYPE_ID", "VALUE_TYPE_NAME", "ORDER_NO", "UNIT", "FROM_CODE", "GIS_ID") AS 
  SELECT 
    "SUBJ_PARAM_ID"
    ,"SUBJ_ID"
    ,"EPI_ID"
    ,"PARAM_TYPE_ID"
    ,PKG_INVENT.LOOKUP_SUPER_TYP_NAME(PARAM_TYPE_ID) AS PARAM_TYPE_NAME 
    ,"VALUE"
    ,"UNIT_TYPE_ID"
    ,PKG_INVENT.LOOKUP_SUPER_TYP_NAME(UNIT_TYPE_ID) AS UNIT_TYPE_NAME 
    ,"DESCRIPTION"
    ,"STATUS_ID"
    ,PKG_INVENT.LOOKUP_SUPER_TYP_NAME(STATUS_ID) AS STAT_TYPE_NAME
    ,"CRU"
    ,"CRD"
    ,"MDU"
    ,"MDD"
    ,"MM_ID"
    ,"VALUE_TYPE_ID"
    ,PKG_INVENT.LOOKUP_SUPER_TYP_NAME(VALUE_TYPE_ID) AS VALUE_TYPE_NAME
    ,"ORDER_NO"
    ,"UNIT"
    ,"FROM_CODE"
    ,"GIS_ID"
FROM
SUBJ_PARAM;
