--------------------------------------------------------
--  DDL for View V_TREATM_TREATM_PARAM
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_TREATM_TREATM_PARAM" ("TREATM_ID", "TREATM_GROUP_ID", "TREATM_TYPE_ID", "TREATM_CATEGORY_ID", "TIME_START", "SUBJ_TYPE_ID", "SUBJ_ID", "PARAM_TYPE_ID") AS 
  SELECT        OBH_TEST.TREATM.TREATM_ID, OBH_TEST.TREATM.TREATM_GROUP_ID, OBH_TEST.TREATM.TREATM_TYPE_ID, OBH_TEST.TREATM.TREATM_CATEGORY_ID, 
                         OBH_TEST.TREATM.TIME_START, OBH_TEST.TREATM_PARAM.SUBJ_TYPE_ID, OBH_TEST.TREATM_PARAM.SUBJ_ID,PARAM_TYPE_ID
FROM            OBH_TEST.TREATM, OBH_TEST.TREATM_PARAM
WHERE        (TREATM.TREATM_ID = TREATM_PARAM.TREATM_ID)
WITH READ ONLY;
