--------------------------------------------------------
--  DDL for View V_TREATM_CHILDS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_TREATM_CHILDS" ("TREATM_ID", "LINK", "TREATM_NAME", "TREATM_GROUP_ID", "TREATM_GROUP_NAME", "TREATM_TYPE_ID", "TREATM_TYPE_NAME", "TREATM_CATEGORY_ID", "TREATM_CATEGORY_NAME", "TYPE1_ID", "TYPE1_NAME", "TYPE2_ID", "TYPE2_NAME", "TREATM_ID1", "TREATM_ID2", "KOD1", "KOD2", "STATUS_ID", "STATUS_NAME", "REL_TYPE_ID", "REL_TYLE_NAME", "TREATM_REL_ID", "ORDER_NO", "EXTRA_NEXT_STEP", "GO_ORDER_NO", "PARENT_NAME", "CHILD_NAME", "PARENT_GROUP_ID", "CHILD_GROUP_ID", "PARENT_GROUP_NAME", "CHILD_GROUP_NAME") AS 
  select TREATM.TREATM_ID as TREATM_ID,
 --      '<a href= "javascript:callMyPopup('||TREATM.TREATM_ID || ')"><img src="'||V('WORKSPACE_IMAGES')||'File_Edit.png"></a>' AS LINK,
       TREATM_REL.TREATM_REL_ID as LINK,
       TREATM.TREATM_NAME as TREATM_NAME,
       TREATM.TREATM_GROUP_ID as TREATM_GROUP_ID,
       lookup_super_type_name(TREATM.TREATM_GROUP_ID) AS TREATM_GROUP_NAME,
       TREATM.TREATM_TYPE_ID as TREATM_TYPE_ID,
       lookup_super_type_name(TREATM.TREATM_TYPE_ID) AS TREATM_TYPE_NAME,
       TREATM.TREATM_CATEGORY_ID as TREATM_CATEGORY_ID,
       lookup_super_type_name(TREATM.TREATM_CATEGORY_ID) AS TREATM_CATEGORY_NAME,
       TREATM.TYPE1_ID as TYPE1_ID,
       lookup_super_type_name(TREATM.TYPE1_ID) AS TYPE1_NAME,
       TREATM.TYPE2_ID as TYPE2_ID,
       lookup_super_type_name(TREATM.TYPE2_ID) AS TYPE2_NAME,
       TREATM_REL.TREATM_ID1 as TREATM_ID1,
       TREATM_REL.TREATM_ID2 as TREATM_ID2,
       TREATM_REL.KOD1 AS KOD1,
       TREATM_REL.KOD2 AS KOD2,
       TREATM_REL.STATUS_ID as STATUS_ID,
       lookup_super_type_name(TREATM_REL.STATUS_ID) AS STATUS_NAME,
       TREATM_REL.REL_TYPE_ID REL_TYPE_ID,
       lookup_super_type_name(TREATM_REL.REL_TYPE_ID) AS REL_TYLE_NAME,
       TREATM_REL.TREATM_REL_ID as TREATM_REL_ID,
       TREATM_REL.ORDER_NO,
       TREATM_REL.EXTRA_NEXT_STEP,
       TREATM_REL.GO_ORDER_NO,
       (SELECT T.TREATM_NAME from TREATM T WHERE T.TREATM_ID = TREATM_REL.TREATM_ID2) AS PARENT_NAME,
       (SELECT T.TREATM_NAME from TREATM T WHERE T.TREATM_ID = TREATM_REL.TREATM_ID1) AS CHILD_NAME,
       (SELECT T.TREATM_GROUP_ID from TREATM T WHERE T.TREATM_ID = TREATM_REL.TREATM_ID2) AS PARENT_GROUP_ID,
       (SELECT T.TREATM_GROUP_ID from TREATM T WHERE T.TREATM_ID = TREATM_REL.TREATM_ID1) AS CHILD_GROUP_ID,
       (SELECT lookup_super_type_name(T.TREATM_GROUP_ID) from TREATM T WHERE T.TREATM_ID = TREATM_REL.TREATM_ID2) AS PARENT_GROUP_NAME,
       (SELECT lookup_super_type_name(T.TREATM_GROUP_ID) from TREATM T WHERE T.TREATM_ID = TREATM_REL.TREATM_ID1) AS CHILD_GROUP_NAME
       
 from TREATM_REL TREATM_REL,
      TREATM TREATM
  WHERE TREATM.TREATM_ID =  TREATM_REL.TREATM_ID1;
