--------------------------------------------------------
--  DDL for View V_USER_EFF_RIGHTS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_USER_EFF_RIGHTS" ("ROLE_USER_ID", "USER_ID", "ROLE_ID", "STAT_TYPE_ID", "FROM_DATE", "TO_DATE", "SUBJ_ORG_ID", "SIGN", "DATA_OWNER_ID", "USER_NAME", "SUBJ_PERSON_ID", "ROLE_NAME", "APEX_PAGE", "APEX_VARIABLE", "TCRITERION") AS 
  SELECT DMRU.ROLE_USER_ID,
       DMRU.USER_ID,
       DMRU.ROLE_ID,
       DMRU.STATUS_ID,
       DMRU.FROM_DATE,
       DMRU.TO_DATE,
       DMRU.SUBJ_ID SUBJ_ORG_ID,
       DMRU.SIGN,
       DMRU.DATA_OWNER_ID,
       DMU.USER_NAME,
       DMU.SUBJ_ID SUBJ_PERSON_ID,
       DMR.ROLE_NAME,
       DMRR.APEX_PAGE,
       DMRR.APEX_VARIABLE,
       DMRR.TCRITERION
  FROM AMNIS.DM_ROLE_USER DMRU,
       AMNIS.DM_USER DMU,
       AMNIS.DM_ROLE DMR,
       AMNIS.DM_ROLE_RIGHT DMRR
  WHERE DMRU.USER_ID = DMU.USER_ID
  AND DMR.ROLE_ID = DMRU.ROLE_ID
  AND DMR.ROLE_ID = DMRR.ROLE_ID;
