--------------------------------------------------------
--  Constraints for Table VALID_UNIT
--------------------------------------------------------

  ALTER TABLE "VALID_UNIT" ADD CONSTRAINT "PK_VALU" UNIQUE ("VALID_UNIT_ID") ENABLE;
 
  ALTER TABLE "VALID_UNIT" MODIFY ("VALID_UNIT_ID" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("UNIT_ID" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("UNIT_NAME" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("UNIT" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("ANALYSIS_TYPE_ID" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("VALID_TYPE_ID" NOT NULL DISABLE);
