--------------------------------------------------------
--  DDL for Table WK_DM_TREATM
--------------------------------------------------------

  CREATE TABLE "WK_DM_TREATM" 
   (	"DM_TREATM_ID" NUMBER(12,0), 
	"TREATM_ID" NUMBER(12,0), 
	"TREATM_TYPE_ID" NUMBER(12,0), 
	"TREATM_CATEGORY_ID" NUMBER(12,0), 
	"TREATM_GROUP_ID" NUMBER(12,0), 
	"TREATM_PARAM_TYPE_ID" NUMBER(12,0), 
	"MANDATORY" NUMBER(1,0) DEFAULT 0, 
	"MULTIPLY" NUMBER(1,0) DEFAULT 0, 
	"TABLE_ROLL" NVARCHAR2(50) DEFAULT 'TEATM_PARAM', 
	"ROLL_TYPE" NUMBER(1,0) DEFAULT 0, 
	"ORDER_NO" NUMBER(4,0), 
	"VALUE_GROUP_ID" NUMBER(12,0), 
	"VALUE_GROUP_TABLE" VARCHAR2(50) DEFAULT 'DM_SUPER_TYP', 
	"VALUE_ALLOWED" NUMBER(1,0) DEFAULT 1, 
	"DIMENSION_GROUP_ID" NUMBER(12,0), 
	"DIMENSION_ALLOWED" NUMBER(1,0), 
	"USER_TYPE1_GROUP" NUMBER(12,0), 
	"USER_TYPE2_GROUP" NUMBER(12,0), 
	"SUBJ_GROUP_ID" NUMBER(12,0), 
	"FROM_DATE" DATE DEFAULT SYSDATE, 
	"TO_DATE" DATE DEFAULT TO_DATE('2099.12.31. 23:59:59','YYYY.MM.DD. HH24:MI:SS'), 
	"DESCRIPTION" VARCHAR2(255), 
	"CRD" TIMESTAMP (6), 
	"CRU" VARCHAR2(30), 
	"MDD" TIMESTAMP (6), 
	"MDU" VARCHAR2(30), 
	"PARAM_VISIBLE" NUMBER(1,0) DEFAULT 1, 
	"VALUE_TYPE" NVARCHAR2(50) DEFAULT 'TEXT'
   ) ;
