--------------------------------------------------------
--  Constraints for Table WK_TREATM_PARAM
--------------------------------------------------------

  ALTER TABLE "WK_TREATM_PARAM" ADD CONSTRAINT "PK_WK_TREATM_PARAM" PRIMARY KEY ("TREATM_PARAM_ID") ENABLE;
 
  ALTER TABLE "WK_TREATM_PARAM" MODIFY ("TREATM_PARAM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "WK_TREATM_PARAM" MODIFY ("EPI_ID" NOT NULL ENABLE);
 
  ALTER TABLE "WK_TREATM_PARAM" MODIFY ("PARAM_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "WK_TREATM_PARAM" MODIFY ("FROM_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "WK_TREATM_PARAM" MODIFY ("TO_DATE" NOT NULL ENABLE);
